# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15fvcAjU2Bz4_TQLyt-LLATFL7FmePnT_
"""

import pickle
import streamlit as st
import numpy as np

# Baca model kamu
model_gemoy = pickle.load(open('23611045_model.sav', 'rb'))

# Judul dan vibes
st.markdown("<h1 style='text-align: center; color: #FF69B4;'>💉 Prediksi Diabetes Versi Gemoy ✨</h1>", unsafe_allow_html=True)
st.markdown("<h5 style='text-align: center; color: #666;'>Isi data kamu dengan jujur ya, biar hasilnya gak ngadi-ngadi 💌</h5>", unsafe_allow_html=True)

st.markdown("---")

# Form lucu
with st.form(key='form_diabetes'):
    st.markdown("### 🌸 Yuk isi dulu data kamu:")

    col1, col2 = st.columns(2)
    with col1:
        Pregnancies = st.number_input("🤰 Kehamilan ke-", min_value=0)
        BloodPressure = st.number_input("🩺 Tekanan Darah (mm Hg)", min_value=0)
        Insulin = st.number_input("💉 Insulin Level", min_value=0)
        DiabetesPedigreeFunction = st.number_input("🧬 Riwayat Diabetes Keluarga", min_value=0.0, format="%.3f")
    with col2:
        Glucose = st.number_input("🍬 Glukosa (mg/dL)", min_value=0)
        SkinThickness = st.number_input("👕 Tebal Lipatan Kulit", min_value=0)
        BMI = st.number_input("⚖️ BMI", min_value=0.0, format="%.1f")
        Age = st.number_input("🎂 Umur", min_value=1)

    submitted = st.form_submit_button("🔮 Cek Prediksi Aku!")

# Hasil prediksi
if submitted:
    input_data = np.array([[Pregnancies, Glucose, BloodPressure, SkinThickness, Insulin,
                            BMI, DiabetesPedigreeFunction, Age]])
    hasil = model_gemoy.predict(input_data)

    if hasil[0] == 1:
        st.markdown("<div style='text-align:center; background-color:#ffcccc; padding:20px; border-radius:10px;'>"
                    "<h3 style='color:#cc0000;'>⚠️ Oops! Prediksinya kamu <u><b>terindikasi diabetes</b></u>.</h3>"
                    "<p>Tapi tenang, ini cuma prediksi ya. Tetap cek ke dokter buat hasil akurat! 💗</p>"
                    "</div>", unsafe_allow_html=True)
    else:
        st.markdown("<div style='text-align:center; background-color:#ccffcc; padding:20px; border-radius:10px;'>"
                    "<h3 style='color:#006600;'>✅ Yeay! Kamu <u><b>tidak terindikasi diabetes</b></u>.</h3>"
                    "<p>Tetap jaga pola hidup sehat yaaa! 🥦🚶‍♀️</p>"
                    "</div>", unsafe_allow_html=True)